coverage:
  status:
    project: off
    patch: off

flags:
  unit:
    carryforward: false
  functional:
    carryforward: false
  integration:
    carryforward: false
  ubuntu:
    carryforward: true
  macos:
    carryforward: true
