__all__ = ["nationalities"]

nationalities = [
    {"id": 0, "name": None, "flag": "🏳️"},
    {"id": 1, "name": "American", "flag": "🇺🇸"},
    {"id": 2, "name": "Argentinean", "flag": "🇦🇷"},
    {"id": 3, "name": "Australian", "flag": "🇦🇺"},
    {"id": 4, "name": "Austrian", "flag": "🇦🇹"},
    {"id": 5, "name": "Azerbaijani", "flag": "🇦🇿"},
    {"id": 6, "name": "Bahraini", "flag": "🇧🇭"},
    {"id": 7, "name": "Belgian", "flag": "🇧🇪"},
    {"id": 8, "name": "Bolivian", "flag": "🇧🇴"},
    {"id": 9, "name": "Brazilian", "flag": "🇧🇷"},
    {"id": 10, "name": "British", "flag": "🇬🇧"},
    {"id": 11, "name": "Bulgarian", "flag": "🇧🇬"},
    {"id": 12, "name": "Cameroonian", "flag": "🇨🇲"},
    {"id": 13, "name": "Canadian", "flag": "🇨🇦"},
    {"id": 14, "name": "Chilean", "flag": "🇨🇱"},
    {"id": 15, "name": "Chinese", "flag": "🇨🇳"},
    {"id": 16, "name": "Colombian", "flag": "🇨🇴"},
    {"id": 17, "name": "Costa Rican", "flag": "🇨🇷"},
    {"id": 18, "name": "Croatian", "flag": "🇭🇷"},
    {"id": 19, "name": "Cypriot", "flag": "🇨🇾"},
    {"id": 20, "name": "Czech", "flag": "🇨🇿"},
    {"id": 21, "name": "Danish", "flag": "🇩🇰"},
    {"id": 22, "name": "Dutch", "flag": "🇳🇱"},
    {"id": 23, "name": "Ecuadorian", "flag": "🇪🇨"},
    {"id": 24, "name": "English", "flag": "🏴󠁧󠁢󠁥󠁮󠁧󠁿"},
    {"id": 25, "name": "Emirian", "flag": "🇦🇪"},
    {"id": 26, "name": "Estonian", "flag": "🇪🇪"},
    {"id": 27, "name": "Finnish", "flag": "🇫🇮"},
    {"id": 28, "name": "French", "flag": "🇫🇷"},
    {"id": 29, "name": "German", "flag": "🇩🇪"},
    {"id": 30, "name": "Ghanaian", "flag": "🇬🇭"},
    {"id": 31, "name": "Greek", "flag": "🇬🇷"},
    {"id": 32, "name": "Guatemalan", "flag": "🇬🇹"},
    {"id": 33, "name": "Honduran", "flag": "🇭🇳"},
    {"id": 34, "name": "Hong Konger", "flag": "🇭🇰"},
    {"id": 35, "name": "Hungarian", "flag": "🇭🇺"},
    {"id": 36, "name": "Icelander", "flag": "🇮🇸"},
    {"id": 37, "name": "Indian", "flag": "🇮🇳"},
    {"id": 38, "name": "Indonesian", "flag": "🇮🇩"},
    {"id": 39, "name": "Irish", "flag": "🇮🇪"},
    {"id": 40, "name": "Israeli", "flag": "🇮🇱"},
    {"id": 41, "name": "Italian", "flag": "🇮🇹"},
    {"id": 42, "name": "Jamaican", "flag": "🇯🇲"},
    {"id": 43, "name": "Japanese", "flag": "🇯🇵"},
    {"id": 44, "name": "Jordanian", "flag": "🇯🇴"},
    {"id": 45, "name": "Kuwaiti", "flag": "🇰🇼"},
    {"id": 46, "name": "Latvian", "flag": "🇱🇻"},
    {"id": 47, "name": "Lebanese", "flag": "🇱🇧"},
    {"id": 48, "name": "Lithuanian", "flag": "🇱🇹"},
    {"id": 49, "name": "Luxembourger", "flag": "🇱🇺"},
    {"id": 50, "name": "Malaysian", "flag": "🇲🇾"},
    {"id": 51, "name": "Maltese", "flag": "🇲🇹"},
    {"id": 52, "name": "Mexican", "flag": "🇲🇽"},
    {"id": 53, "name": "Monegasque", "flag": "🇲🇨"},
    {"id": 54, "name": "New Zealander", "flag": "🇳🇿"},
    {"id": 55, "name": "Nicaraguan", "flag": "🇳🇮"},
    {"id": 56, "name": "Northern Irish", "flag": "🇮🇪"},
    {"id": 57, "name": "Norwegian", "flag": "🇳🇴"},
    {"id": 58, "name": "Omani", "flag": "🇴🇲"},
    {"id": 59, "name": "Pakistani", "flag": "🇵🇰"},
    {"id": 60, "name": "Panamanian", "flag": "🇵🇦"},
    {"id": 61, "name": "Paraguayan", "flag": "🇵🇾"},
    {"id": 62, "name": "Peruvian", "flag": "🇵🇪"},
    {"id": 63, "name": "Polish", "flag": "🇵🇱"},
    {"id": 64, "name": "Portuguese", "flag": "🇵🇹"},
    {"id": 65, "name": "Qatari", "flag": "🇶🇦"},
    {"id": 66, "name": "Romanian", "flag": "🇷🇴"},
    {"id": 67, "name": "Russian", "flag": "🇷🇺"},
    {"id": 68, "name": "Salvadoran", "flag": "🇸🇻"},
    {"id": 69, "name": "Saudi", "flag": "🇸🇦"},
    {"id": 70, "name": "Scottish", "flag": "🏴󠁧󠁢󠁳󠁣󠁴󠁿"},
    {"id": 71, "name": "Serbian", "flag": "🇷🇸"},
    {"id": 72, "name": "Singaporean", "flag": "🇸🇬"},
    {"id": 73, "name": "Slovakian", "flag": "🇸🇰"},
    {"id": 74, "name": "Slovenian", "flag": "🇸🇮"},
    {"id": 75, "name": "South Korean", "flag": "🇰🇷"},
    {"id": 76, "name": "South African", "flag": "🇿🇦"},
    {"id": 77, "name": "Spanish", "flag": "🇪🇸"},
    {"id": 78, "name": "Swedish", "flag": "🇸🇪"},
    {"id": 79, "name": "Swiss", "flag": "🇨🇭"},
    {"id": 80, "name": "Thai", "flag": "🇹🇭"},
    {"id": 81, "name": "Turkish", "flag": "🇹🇷"},
    {"id": 82, "name": "Uruguayan", "flag": "🇺🇾"},
    {"id": 83, "name": "Ukrainian", "flag": "🇺🇦"},
    {"id": 84, "name": "Venezuelan", "flag": "🇻🇪"},
    {"id": 85, "name": "Barbadian", "flag": "🇧🇧"},
    {"id": 86, "name": "Welsh", "flag": "🏴󠁧󠁢󠁷󠁬󠁳󠁿"},
    {"id": 87, "name": "Vietnamese", "flag": "🇻🇳"},
]
