---
name: Package
description: Install python and package
runs:
    using: "composite"
    steps:
      - name: Install Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: Install package
        run: pip install -e .[dev]
        shell: bash
