---
name: Package
description: Install python and package
runs:
    using: "composite"
    steps:
      - name: Install Python 3.10
        id: setup-python
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
        shell: bash

      - uses: actions/cache@v3
        id: cache
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-python-${{ steps.setup-python.outputs.python-version }}-${{ hashFiles('pyproject.toml') }}-${{ steps.date.outputs.date }}

      - name: Install package
        if: steps.cache.outputs.cache-hit != 'true'
        run: pip install --upgrade -e .[dev]
        shell: bash
