__all__ = ["infringements"]

infringements = [
    {"id": 0, "name": "Blocking by slow driving"},
    {"id": 1, "name": "Blocking by wrong way driving"},
    {"id": 2, "name": "Reversing off the start line"},
    {"id": 3, "name": "Big Collision"},
    {"id": 4, "name": "Small Collision"},
    {"id": 5, "name": "Collision failed to hand back position single"},
    {"id": 6, "name": "Collision failed to hand back position multiple"},
    {"id": 7, "name": "Corner cutting gained time"},
    {"id": 8, "name": "Corner cutting overtake single"},
    {"id": 9, "name": "Corner cutting overtake multiple"},
    {"id": 10, "name": "Crossed pit exit lane"},
    {"id": 11, "name": "Ignoring blue flags"},
    {"id": 12, "name": "Ignoring yellow flags"},
    {"id": 13, "name": "Ignoring drive through"},
    {"id": 14, "name": "Too many drive throughs"},
    {"id": 15, "name": "Drive through reminder serve within n laps"},
    {"id": 16, "name": "Drive through reminder serve this lap"},
    {"id": 17, "name": "Pit lane speeding"},
    {"id": 18, "name": "Parked for too long"},
    {"id": 19, "name": "Ignoring tyre regulations"},
    {"id": 20, "name": "Too many penalties"},
    {"id": 21, "name": "Multiple warnings"},
    {"id": 22, "name": "Approaching disqualification"},
    {"id": 23, "name": "Tyre regulations select single"},
    {"id": 24, "name": "Tyre regulations select multiple"},
    {"id": 25, "name": "Lap invalidated corner cutting"},
    {"id": 26, "name": "Lap invalidated running wide"},
    {"id": 27, "name": "Corner cutting ran wide gained time minor"},
    {"id": 28, "name": "Corner cutting ran wide gained time significant"},
    {"id": 29, "name": "Corner cutting ran wide gained time extreme"},
    {"id": 30, "name": "Lap invalidated wall riding"},
    {"id": 31, "name": "Lap invalidated flashback used"},
    {"id": 32, "name": "Lap invalidated reset to track"},
    {"id": 33, "name": "Blocking the pitlane"},
    {"id": 34, "name": "Jump start"},
    {"id": 35, "name": "Safety car to car collision"},
    {"id": 36, "name": "Safety car illegal overtake"},
    {"id": 37, "name": "Safety car exceeding allowed pace"},
    {"id": 38, "name": "Virtual safety car exceeding allowed pace"},
    {"id": 39, "name": "Formation lap below allowed speed"},
    {"id": 40, "name": "Retired mechanical failure"},
    {"id": 41, "name": "Retired terminally damaged"},
    {"id": 42, "name": "Safety car falling too far back"},
    {"id": 43, "name": "Black flag timer"},
    {"id": 44, "name": "Unserved stop go penalty"},
    {"id": 45, "name": "Unserved drive through penalty"},
    {"id": 46, "name": "Engine component change"},
    {"id": 47, "name": "Gearbox change"},
    {"id": 48, "name": "League grid penalty"},
    {"id": 49, "name": "Retry penalty"},
    {"id": 50, "name": "Illegal time gain"},
    {"id": 51, "name": "Mandatory pitstop"},
]
