__all__ = ["teams"]

teams = [
    {"id": 0, "name": "Mercedes"},
    {"id": 1, "name": "Ferrari"},
    {"id": 2, "name": "Red Bull Racing"},
    {"id": 3, "name": "Williams"},
    {"id": 4, "name": "Aston Martin"},
    {"id": 5, "name": "Alpine"},
    {"id": 6, "name": "Alpha Tauri"},
    {"id": 7, "name": "Haas"},
    {"id": 8, "name": "McLaren"},
    {"id": 9, "name": "Alfa Romeo"},
    {"id": 42, "name": "Art GP ’19"},
    {"id": 43, "name": "Campos ’19"},
    {"id": 44, "name": "Carlin ’19"},
    {"id": 45, "name": "Sauber Junior Charouz ’19"},
    {"id": 46, "name": "Dams ’19"},
    {"id": 47, "name": "Uni-Virtuosi ‘19"},
    {"id": 48, "name": "MP Motorsport ‘19"},
    {"id": 49, "name": "Prema ’19"},
    {"id": 50, "name": "Trident ’19"},
    {"id": 51, "name": "Arden ’19"},
    {"id": 70, "name": "Art GP ‘20"},
    {"id": 71, "name": "Campos ‘20"},
    {"id": 72, "name": "Carlin ‘20"},
    {"id": 73, "name": "Charouz ‘20"},
    {"id": 74, "name": "Dams ‘20"},
    {"id": 75, "name": "Uni-Virtuosi ‘20"},
    {"id": 76, "name": "MP Motorsport ‘20"},
    {"id": 77, "name": "Prema ‘20"},
    {"id": 78, "name": "Trident ‘20"},
    {"id": 79, "name": "BWT ‘20"},
    {"id": 80, "name": "Hitech ‘20"},
    {"id": 85, "name": "Mercedes 2020"},
    {"id": 86, "name": "Ferrari 2020"},
    {"id": 87, "name": "Red Bull 2020"},
    {"id": 88, "name": "Williams 2020"},
    {"id": 89, "name": "Racing Point 2020"},
    {"id": 90, "name": "Renault 2020"},
    {"id": 91, "name": "Alpha Tauri 2020"},
    {"id": 92, "name": "Haas 2020"},
    {"id": 93, "name": "McLaren 2020"},
    {"id": 94, "name": "Alfa Romeo 2020"},
]
