__all__ = ["tracks"]

tracks = [
    {"id": 0, "name": "Melbourne"},
    {"id": 1, "name": "Paul Ricard"},
    {"id": 2, "name": "Shanghai"},
    {"id": 3, "name": "Sakhir (Bahrain) "},
    {"id": 4, "name": "Catalunya"},
    {"id": 5, "name": "Monaco"},
    {"id": 6, "name": "Montreal"},
    {"id": 7, "name": "Silverstone"},
    {"id": 8, "name": "Hockenheim"},
    {"id": 9, "name": "Hungaroring"},
    {"id": 10, "name": "Spa"},
    {"id": 11, "name": "Monza"},
    {"id": 12, "name": "Singapore"},
    {"id": 13, "name": "Suzuka"},
    {"id": 14, "name": "Abu Dhabi"},
    {"id": 15, "name": "Texas"},
    {"id": 16, "name": "Brazil"},
    {"id": 17, "name": "Austria"},
    {"id": 18, "name": "Sochi"},
    {"id": 19, "name": "Mexico"},
    {"id": 20, "name": "Baku (Azerbaijan)"},
    {"id": 21, "name": "Sakhir Short"},
    {"id": 22, "name": "Silverstone Short"},
    {"id": 23, "name": "Texas Short"},
    {"id": 24, "name": "Suzuka Short"},
    {"id": 25, "name": "Hanoi"},
    {"id": 26, "name": "Zandvoort"},
    {"id": 27, "name": "Imola"},
    {"id": 28, "name": "Portimão"},
    {"id": 29, "name": "Jeddah"},
]
