name: release

on:
  pull_request:
  push:
    branches: [master]

jobs:
  pypi:
    runs-on: ubuntu-latest
#    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
    steps:
      - name: Wait for other checks to succeed
        uses: lewagon/wait-on-check-action@v1.0.0
        with:
          ref: ${{ github.ref }}
          running-workflow-name: 'Publish the package'
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          wait-interval: 10

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: Install and configure Poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-create: false
          installer-parallel: true

      - name: Build package
        run: poetry build

      - name: Uploading to PyPI
        run: echo "Uploading to PYPI"
