name: unit

on:
  pull_request:
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: Install and configure Poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-create: false
          installer-parallel: true

      - name: Install package
        run: poetry install --with dev

      - name: Run unit tests
        run: poetry run coverage run --source='src/' -m pytest tests/unit

      - name: Prepare coverage report
        run: poetry run coverage report -m

      - name: Upload coverage report do Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage.xml
          flags: unit
#          name: codecov-umbrella # optional
          fail_ci_if_error: true # optional (default = false)
          verbose: true # optional (default = false)
