name: functional

on:
  repository_dispatch:
    types: [ full-tests-command ]
  pull_request:
  push:
    branches:
      - master
    tags:
      - "*"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Add reaction
        if: ${{ github.event.repository_dispatch.type == 'full-tests-command' }}
        uses: peter-evans/create-or-update-comment@v2
        with:
          comment-id: ${{ github.event.client_payload.github.payload.comment.id }}
          reaction-type: hooray

      - name: Create URL to the run output
        if: ${{ github.event.repository_dispatch.type == 'full-tests-command' }}
        id: vars
        run: echo "run-url=https://github.com/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID" >> $GITHUB_OUTPUT

      - name: Create comment
        if: ${{ github.event.repository_dispatch.type == 'full-tests-command' }}
        uses: peter-evans/create-or-update-comment@v2
        with:
          issue-number: ${{ github.event.client_payload.github.payload.issue.number }}
          body: |
            Hello @${{ github.event.client_payload.github.actor }}!
            [Click here to see the command run output][1]
            [1]: ${{ steps.vars.outputs.run-url }}

      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Prepare package
        uses: ./.github/actions/package

      - name: Run functional tests
        run: coverage run --source='src/' -m behave

      - name: Coverage report
        uses: ./.github/actions/coverage
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          flags: functional
