name: functional

on:
  pull_request:
  push:
    branches:
      - master
    tags:
      - "*"

jobs:
  call-another:
    uses: ./.github/workflows/integration-tests.yml
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            python-version: '3.10'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Prepare package
        uses: ./.github/actions/package

      - name: Run functional tests
        run: coverage run --source='src/' -m behave

      - name: Coverage report
        uses: ./.github/actions/coverage
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          flags: functional
