name: functional

on:
  pull_request:
  push:
    branches:
      - master
    tags:
      - "*"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Prepare package
        uses: ./.github/actions/package

      - name: Run functional tests
        run: poetry run coverage run --source='src/' -m behave

      - name: Coverage report
        uses: ./.github/actions/coverage
