name: help-command

on:
  repository_dispatch:
    types: [help-command]

jobs:
  help:
    runs-on: ubuntu-latest
    steps:
      - name: Update comment
        uses: peter-evans/create-or-update-comment@v3
        with:
          token: ${{ secrets.NEPTUNE_BOT_ACCESS_TOKEN }}
          comment-id: ${{ github.event.client_payload.github.payload.comment.id }}
          body: |
            > Command | Description
            > --- | ---
            > /pre-commit-apply | Commit a pre-commit suggestions
            > /full-tests | Run tests on full matrix
          reaction-type: hooray
