name: integration

on:
  pull_request:
  push:
    branches:
      - master
    tags:
      - "*"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Prepare package
        uses: ./.github/actions/package

      - name: Run integration tests
        run: poetry run coverage run --source='src/' -m pytest tests/integration

      - name: Coverage report
        uses: ./.github/actions/coverage
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          flags: integration
