name: mypy

on:
  pull_request:
  push:
    branches:
      - master
    tags:
      - "*"

jobs:
  mypy:
    runs-on: ubuntu-latest
    steps:
      - name: Prepare package
        uses: ./.github/actions/package

      - name: Run tests
        run: poetry run mypy .
