name: release

on:
  push:
    branches:
      - master

jobs:
  pypi:
    name: Publish the package
    runs-on: ubuntu-latest
    steps:
#      - name: Wait for other checks to succeed
#        uses: lewagon/wait-on-check-action@v1.0.0
#        with:
#          ref: ${{ github.ref }}
#          running-workflow-name: 'Publish the package'
#          repo-token: ${{ secrets.GITHUB_TOKEN }}
#          wait-interval: 10

      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          # We need to fetch all history to retrieve the latest tag
          fetch-depth: 0

      - name: Install Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: Install and configure Poetry
        uses: snok/install-poetry@v1.3.1
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true
          installer-parallel: true

      - name: Git log
        run: git describe --tags

      - name: Install package
        run: pip install -e .

      - name: AAA
        run: python -m pip install --upgrade -q pip

      - name: ZZZ
        run: pip install build poetry-dynamic-versioning

      - name: Build package with pip
        run: python -m build --sdist --wheel

      - name: List directory
        run: ls -a

      - name: Build package
        run: |
          source .venv/bin/activate
          poetry version

#      - name: Uploading to test PyPI
#        uses: pypa/gh-action-pypi-publish@release/v1
#        with:
#          user: __token__
#          password: ${{ secrets.TEST_PYPI_API_TOKEN }}
#          repository_url: https://test.pypi.org/legacy/
#
#      - name: Uploading to PyPI
#        uses: pypa/gh-action-pypi-publish@release/v1
#        with:
#          user: __token__
#          password: ${{ secrets.PYPI_API_TOKEN }}
