name: release

on:
  push:
    tags:
      - "*"

jobs:

  validate-version:
    runs-on: ubuntu-latest
    steps:
      - uses: rubenesp87/semver-validation-action@0.1.0
        with:
          version: ${{ github.ref_name }}

  wait-for-green-master:
    runs-on: ubuntu-latest
    steps:
      - name: Wait for tests to finish
        uses: lewagon/wait-on-check-action@v1.3.1
        with:
          ref: ${{ github.ref }}
          running-workflow-name: 'wait-for-green-master'
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          wait-interval: 10

  publish:
    name: publish
    needs: [ validate-version, wait-for-green-master ]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install build dependencies
        run: pip install poetry poetry-dynamic-versioning

      - name: Build package
        run: poetry build

      - name: Uploading to test PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.TEST_PYPI_API_TOKEN }}
          repository_url: https://test.pypi.org/legacy/

      - name: Uploading to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
