name: Slash Command Dispatch

on:
  issue_comment:
    types: [created]

jobs:
  slash-dispatch:
    runs-on: ubuntu-latest
    steps:
      - name: Slash Command Dispatch
        uses: peter-evans/slash-command-dispatch@v3
        with:
          commands: |
            hello2
            hello1
          reaction-token: ${{ secrets.NEPTUNE_BOT_ACCESS_TOKEN }}
          token: ${{ secrets.NEPTUNE_BOT_ACCESS_TOKEN }}
