name: unit

on:
  workflow_dispatch:
  workflow_call:
  pull_request:
  push:
    branches:
      - master
    tags:
      - "*"

jobs:
  test:
    strategy:
        fail-fast: false
        matrix:
          os: [ubuntu, macos]
    runs-on: ${{ matrix.os }}-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.event.client_payload.pull_request.head.ref }}

      - name: Prepare package
        uses: ./.github/actions/package

      - name: Run unit tests
        run: coverage run --source='src/' -m pytest tests/unit

      - name: Coverage report
        uses: ./.github/actions/coverage
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          flags: unit,${{ matrix.os }}
